---
Name: flagcommentsconfig
---

SilverStripe\Comments\Extensions\CommentsExtension:
  comments:
    can_flag: false

SilverStripe\Comments\Model\Comment:
  extensions:
    - 'NZTA\FlagComments\Extensions\FlagCommentExtension'

SilverStripe\Comments\Controllers\CommentingController:
  extensions:
    - 'NZTA\FlagComments\Extensions\FlagCommentControllerExtension'
